config/urls.py
from django.contrib import admin
from django.urls import path, include
from sales.views import base_views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sales/', include('sales.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # / 페이지에 해당하는 urlpatterns
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name='sales'

urlpatterns=[
    # base_views.py
    path('',base_views.index, name='index'),
    path('<int:question_id>/',base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',question_views.question_create,name='question_create'),
    path('question/modify/<int:question_id>', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
]

sales/models.py
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    hcode = models.CharField(max_length=10, unique=True)

    wname = models.TextField(max_length=20)
    wplace = models.TextField(max_length=20)
    port = models.TextField(max_length=20)

    author=models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='author_question')

    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True) # Null,blank = True를 기재하지 않아서 인자가 전달되지 않을 수 있다.
    upload_imgfile = models.ImageField(upload_to="question/%Y%m%d", max_length=500,
                                       null=True, blank=True)

    def __str__(self):
        return self.wname+" "+self.wplace+" "+self.port+" "

    def publish(self):
        self.published_date=timezone.now()
        self.save()

class Answer(models.Model):
    damage_result=models.TextField(null=True, blank=True)

    wname = models.TextField(max_length=20)
    wplace = models.TextField(max_length=20)
    port = models.TextField(max_length=20)

    author=models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='author_answer')

    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    predicted_imgfile = models.ImageField(upload_to="", max_length=500, 
                                null=True, blank=True)

    question=models.ForeignKey(Question,on_delete=models.CASCADE)

    def __str__(self):
        return self.wname+" "+self.wplace+" "+self.port+" "+self.damage_result+" "
# 이 코드는 상품 정보를 문자열 형식으로 반환합니다. 각 필드 값 사이에 공백(" ")을 추가하여 구분

    def publish(self):
        self.published_date=timezone.now()
        self.save()  # 현재 객체의 published_date 필드를 현재 시간으로 설정하고 객체를 저장

sales/forms.py
from django import forms
from sales.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model=Question
        fields=['wname','wplace','port','upload_imgfile']
        # widgets={
        #     'subject':forms.TextInput(attrs={'class':'form=control'}),
        #     'content':forms.Textarea(attrs={'class':'from-control','rows':10}),
        # }
        labels={
            'wname':'이용자',
            'wplace' : '지역',
            'port' : '건물',
            'upload_imgfile' : '이미지',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model=Answer
        fields=['predicted_imgfile','damage_result']
        labels={
            'predicted_imgfile':'이미지',
            'damage_result':'인원 수'
        }

sales/views/answer_views.py
from django.contrib import messages # '수정권한이 없습니다' 오류 메세지 발생시키기 위해
from django.contrib.auth.decorators import login_required # @login_required 애더네이션 적용하기
from django.shortcuts import render, get_object_or_404, redirect, resolve_url 
from django.utils import timezone # 현재시간 timezone.now() 사용하기 위해

from ..models import Question, Answer
from ..forms import AnswerForm

@login_required(login_url='common:login')
def answer_create(request, question_id, result_mesg, out_file): # 인자가 어디에서 전달되는가?
    """
    sales 답변 등록
    """
    question=get_object_or_404(Question, pk=question_id)
    # question.answer_set.create(hcode=request.POST.get('hcode'),
    #                            create_date=timezone.now())
    if request.method == "POST":
        form=AnswerForm(request.POST)
        if form.is_valid():           
            answer=form.save(commit=False) # create_date가 지정될 때까지 임시저장
            answer.damage_result=result_mesg
            answer.predicted_imgfile=out_file
            answer.author=request.user # 추가한 속성 author 적용
            answer.create_date=timezone.now()
            answer.question=question
            answer.save()
            return redirect('sales:detail', question_id=question.id)
    else:
        form=AnswerForm()
    context={'question':question,'form':form}
    return render(request, 'sales/question_detail.html', context) ##### answer_form으로 변경해라 난중에

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    sales 답변 수정
    """
    answer=get_object_or_404(Answer,pk=answer_id)
    if request.user !=answer.author:
        messages.error(request,'수정권한이 없습니다')
        return redirect('sales:detail',question_id=answer.question.id)

    if request.method == "POST":
        form=AnswerForm(request.POST,instance = answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author=request.user
            answer.modify_date=timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('sales:detail',question_id=answer.question.id),answer.id))
    else:
        form = AnswerForm(instance=answer)
    context={'answer':answer,'form':form}
    return render(request,'sales/question_form.html',context)

@login_required(login_url = 'common:login')
def answer_delete(request,answer_id):
    """
    sales 답변 삭제
    """
    answer=get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'삭제 권한이 없습니다')
    else:
        answer.delete()
    return redirect('sales:detail',question_id=answer.question.id)

sales/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question, Answer

# Create your views here.
def index(request):
    """
    sales 목록 출력
    """
    # 입력 인자
    page=request.GET.get('page','1') # 페이지

    # 조회
    question_list=Question.objects.order_by('hcode')

    # 페이징 처리
    paginator=Paginator(question_list, 10) # 페이지당 10개씩 보여주기
    page_obj=paginator.get_page(page) # 페이지 번호를 인수로 받아 해당 페이지의 객체 목록을 반환

    context={'question_list':page_obj}
    return render(request, 'sales/question_list.html',context)

def detail(request,question_id):
    """
    sales 내용 출력
    """
    question=get_object_or_404(Question, pk=question_id)
    context={'question':question}
    return render(request, 'sales/question_detail.html', context)

sales/views/question_views.py
from django.contrib import messages # '수정권한이 없습니다' 오류 메세지 발생시키기 위해
from django.contrib.auth.decorators import login_required # @login_required 애더네이션 적용하기
from django.shortcuts import render, get_object_or_404, redirect 
from django.utils import timezone # 현재시간 timezone.now() 사용하기 위해

from ..models import Question
from ..forms import QuestionForm
from .answer_views import *

import os
import ultralytics # YOLO 라이브러리 import
from ultralytics import YOLO
import cv2
from PIL import Image, ImageFont, ImageDraw
import numpy as np
from datetime import datetime

# Create your views here.

# class별 건수 및 전체 건수 계산 함수
def count_objects(results, target_classes):

    total_counts = 0
    object_counts = {x: 0 for x in target_classes} # 0 으로 초기화

    for result in results: # predict() 결과가 저장된 results 변수 반복문
         for c in result.boxes.cls: # 예측결과에서 각 객체의 클래스ID
            c = int(c) # float타입 -> 정수형으로 변환
            '''
            target_classes : predict()에 넘겨준 관심 classes=[] 저장 리스트
            object_counts : 각 클래스별 객체 개수를 저장하는 딕셔너리
            '''
            if c in target_classes:
                object_counts[c] += 1
            elif c not in target_classes:
                object_counts[c] = 0

    for i in object_counts:
        if object_counts[i] >= 1 :
            total_counts += object_counts[i]

    return object_counts[3],total_counts # [halibut]마리, 전체 건수

# 이미지에 counter 넣기 함수
def plot_counter1(img, text1): # text 1 줄만 넣기
    font= cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 1
    color = (0,255,0)
    thickness = 2

    h, w, c = img.shape # 이미지 크기(모양)를 읽어오자
    # c= img.shape

    # 문자 넣을 x,y 위치 정하기
    org1_x = org2_x = w - 330
    org1_y = h - 30
    org1 =  (org1_x, org1_y)

    # img 변수가 NumPy 배열인지 확인
    if not isinstance(img, np.ndarray):
        # img_nparray = np.array(img)
        # img_nparray = np.asarray(img)
        raise TypeError("img 변수가 NumPy 배열이 아닙니다.")

    cv2.putText(img,text1,org1,font,fontScale,color,thickness,cv2.LINE_AA)

    # 이미지 출력해보자
    # cv2.imshow('Image', img) # colab 이외 환경 (vscode, jupyter notebook 등)

# 추론/예측 함수
def yolo_predict(filename, user):

    source_path = './media/' + str(filename) # 경로 포함 파일이름
    predict_dir = './media/answer/'

    source_file = os.path.split(source_path)[1] # 순수 파일이름만
    predict_file = timezone.now().strftime("%Y%m%d") # %H%M
    
    out_file = predict_dir + predict_file + '/' + source_file
    # print
    predict_image_url = 'answer/' + predict_file + '/' + source_file
    # print(장고에는 answer부터 있어야 한다) * 미디어부터 있으면 장고가 인식을 못한다

    choice = False

    if choice : # YOLOv8 original 모델 그대로 사용
        yolo_model = YOLO('yolov8n.pt') 

    else : # 전이학습 : YOLOv8 pretrained 모델 지정
        # pretrained_model = 'C:/projects/crowds/YOLOv8/best.pt'
        pretrained_model = './media/weights/best_30.pt'
        yolo_model = YOLO(pretrained_model) # 전이학습용

    # predict 예측/추론하기
    results = yolo_model.predict(source=source_path, conf=0.30,save=True,
                                 project=predict_dir, name=predict_file, 
                                 exist_ok=True, seed=0, show_conf=False)

    # object detection 결과 : person, 전체 건수 계산
    halibut_count, total_counts = count_objects(results, yolo_model.names)

    # 이미지에 person 건수 쓰기
    cv2_image = cv2.imread(out_file)
    out_text1 = f'      [{halibut_count}] halibut' # 이미지에 출력
    plot_counter1(cv2_image, out_text1)
    cv2.imwrite(out_file, cv2_image)

    # result_mesg = f'YOLOv8 분석 내용 : [{halibut_count}] 명'
    result_mesg = f'[{halibut_count}] 명'
    return result_mesg, predict_image_url

@login_required(login_url='common:login')
def question_create(request):
    """
    sales 질문 등록
    """
    def _generate_next_hcode(last_hcode):
        """
        마지막 hcode로부터 다음 hcode를 생성
        """
        alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        if not last_question:
            return 'H0001'

        last_hcode = last_question.hcode
        number = int(last_hcode[1:]) + 1
        next_hcode = f"H{number:04}"

        if number > len(alphabet):
            next_hcode = f"{alphabet[number // len(alphabet)]}{next_hcode}"
        return next_hcode

    if request.method == 'POST':
        form=QuestionForm(request.POST,request.FILES)
        if form.is_valid():
            question=form.save(commit=False)
            question.upload_imgfile = request.FILES['upload_imgfile']
            question.author=request.user # 추가한 속성 author 적용
            question.create_date=timezone.now()

            # hcode 생성
            # question.hcode = _generate_next_hcode()

            last_question = Question.objects.order_by('hcode').last()
            if last_question:
                question.hcode = _generate_next_hcode(last_question.hcode)  # last_hcode 인수 전달
            else:
                question.hcode = 'H0001'

            question.save()

            # ======= YOLOv8 predict() 후에 답변을 자동 생성할까? ========== 

        # if (question.upload_imgfile.size > 0) : # 파일이 정상적으로 업로드 되었는 지
            result_mesg, out_file = yolo_predict(question.upload_imgfile, request.user)
            # print(type(result_mesg))
            # print(type(out_file))
            # img=cv2.imread('example.jpg', cv2.IMREAD_COLOR)
            # print("이미지의 데이터 타입:", img.dtype)
            # print("이미지의 형태:", img.shape)

            answer_create(request, question.id, result_mesg, out_file) ### result_mesg, predict_image_url 반환 지점

            return redirect('sales:index')

    else:
        form=QuestionForm()
    context={'form':form}
    return render(request,'sales/question_form.html',context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    sales 질문 수정
    """
    question=get_object_or_404(Question,pk=question_id)
    if request.user != question.author:
        messages.error(request,'수정권한이 없습니다')
        return redirect('sales:detail',question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question=form.save(commit=False)
            question.author=request.user
            question.modify_date=timezone.now() # 수정일시 저장
            question.save()
            return redirect('sales:detail',question_id=question.id)

    else:
        form=QuestionForm(instance=question)
    context={'form':form}
    return render(request, 'sales/question_form.html',context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    sales 질문 삭제
    """
    question=get_object_or_404(Question,pk=question_id)
    if request.user != question.author:
        messages.error(request,'삭제권한이 없습니다')
        return redirect('sales:detail',question_id=question.id)
    question.delete()
    return redirect('sales:index')

templates/sales/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 사용자 오류 표시 -->
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
                <strong>{{ message.tags }}</strong>
                <ul><li>{{ message.message }}</li></ul>
            {% endfor %}
        </div>
    {% endif %}
    <h2 class="border-bottom py-2"> <strong>사람 ID : {{ question.hcode }}</strong></h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">
                <div>
                    {% if question.upload_imgfile == '' or question.upload_imgfile == null %}
                    {% else %}
                    <tr>
                        <td colspan="2"><img src="{{ question.upload_imgfile.url }}"
                                             style="max-width:400px"></td>
                    </tr>
                    {% endif %}
                </div>
                <div id="text1">
                    <strong> 이용자 : {{ question.wname }} </strong>
                </div>
                <div id="text2">
                    <strong> 지역 : {{ question.wplace }} </strong>
                </div>
                <div id="text3">
                    <strong> 건물명 : {{ question.port }} </strong>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end">
        {% if question.modify_date %}
        <div class="badge badge-light p-2 text-left mx-3">
            <div class="mb-2">modified at</div>
            <div>{{ question.modify_date }}</div>
        </div>
        {% endif %}
        <div class="badge badge-light p-2 text-left">
            <div class="mb-2">{{ question.author.username }}</div>
            {{ question.create_date|date }}
        </div>
        </div>
        {% if request.user == question.author %}
        <div class="my-3">
            <a href="{% url 'sales:question_modify' question.id %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{% url 'sales:question_delete' question.id %}">삭제</a>
        </div>
        {% endif %}
    </div>

    <h2 class="border-bottom my-3 py-2">
        <strong>{{ question.answer_set.count }}개의 답변이 있습니다.</strong>
    </h2>


    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">
                <div>
                    {% if answer.predicted_imgfile == '' or answer.predicted_imgfile == null %}
                    {% else %}
                    <tr>
                        <td colspan="2"><img src="{{ answer.predicted_imgfile.url }}"
                                             style="max-width:400px"></td>
                    </tr>
                    {% endif %}
                </div>
                <div id="text1">
                    <strong> 인원수 : {{ answer.damage_result }} </strong>
                </div>
                <div id="text2">
                    <strong> 인원수 : {{ answer.wname }} </strong>
                </div>
                <!-- <div id="text3">
                    <strong> 인원 : {{ answer.wplace }} </strong>
                </div> -->
            </div>
            {% if request.user.is_superuser %} <!--수정과 삭제를 관리자 권한으로 변경-->
            <div class="my-3">
                <a href="{% url 'sales:answer_modify' answer.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'sales:answer_delete' answer.id %}">삭제</a>
            </div>
            {% endif %}
        </div>
        <div class="d-flex justify-content-end">
            {% if question.modify_date %}
            <div class="badge badge-light p-2 text-left mx-3">
                <div class="mb-2">modified at</div>
                <div>{{ question.modify_date }}</div>
            </div>
            {% endif %}
            <div class="badge badge-light p-2 text-left">
                <div class="mb-2">{{ answer.author.username }}</div>
                {{ answer.create_date|date }}
            </div>
        </div>
    </div>

    {% endfor %}
    <form action="{% url 'sales:answer_create' question.id %}"
          method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <!-- <a href="{% url 'sales:answer_create' question.id %}" class="btn btn-primary"
           style="background-color:#02075D; color:#ffffff">
            답변 등록
        </a> -->
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/sales/question_detail2.html
{% extends 'base.html' %}
{% load sales_filter %}
{% block content %}
<div class="container my-3">
    <!-- 사용자 오류 표시 -->
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
                <strong>{{ message.tags }}</strong>
                <ul><li>{{ message.message }}</li></ul>
            {% endfor %}
        </div>
    {% endif %}
    <h5 class="border-bottom py-2">{{ question.hcode }}</h5> <!-- 재목 -->
    <!-- 질문 추천 버튼 만들기 -->
    <div class="row my-3">
        <div class="col-11"> <!-- 질문 영역 -->
            <!-- 기존 내용 start -->
            <div class="card"> <!-- my-3 삭제 -->
                <div class="card-body">
                    <div class="card-text">{{ question.hcode|mark }}</div> <!-- markdown 적용 -->
                    
                    <!-- 제보이미지 보여주기 start -->
                    <div>
                    {% if question.upload_imgfile %}
                        <div class="container border col-10">
                            <div style="width:10%; height:150px; float:left; margin-right:10px;">
                                <img src="{{ question.upload_imgfile.url }}" width="400">
                            </div>
                        </div>
                    {% endif %}
                    </div>
                    <!-- 제보이미지 보여주기 end -->

                    <br></br>
                    <p></p>
                    <br></br>

                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                            <!-- 질문 삭제 버튼 추가하기 : 로그인한 사용자와 글쓴이가 같은 경우에만 -->
                            {% if request.user == question.author %}
                            <div class="my-3">
                                <a href="#" class="delete btn btn-sm btn-outline-secondary right"
                                    data-uri="{% url 'sales:question_delete' question.id %}">삭제</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>

                </div>
            </div>
            <!-- 기존 내용 end -->
            
            </div>
        </div>
    </h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a> <!-- 앵커 엘리먼트 추가 -->

    <!-- 답변 추천 버튼 만들기 -->
    <div class="row my-3">
        <div class="col-11"> <!-- 답변 영역 -->
            <!-- 기존 내용 start -->
            <div class="card"> <!-- my-3 삭제 -->
                <div class="card-body">
                    <div class="card-text">{{ answer.hcode|mark }}</div> <!-- markdown 적용 -->

                    <!-- 밀집도 이미지 보여주기 start -->
                    <div>
                        {% if answer.predicted_imgfile %}
                            <div class="container border col-10">
                                <div style="width:10%; height:150px; float:left; margin-right:10px;">
                                    <img src="{{ answer.predicted_imgfile.url }}" width="400">
                                </div>
                            </div>
                        {% endif %}
                        </div>
                    <!-- 밀집도 이미지 보여주기 end -->

                    <br></br>
                    <p></p>
                    <br></br>

                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                            {% if request.user == answer.author %}
                            <div class="my-3">
                                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                                    data-uri="{% url 'sales:answer_delete' answer.id %}">삭제</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>

                </div>
            </div>
            <!-- 기존 내용 end -->
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });     
    });
</script>
{% endblock %}

templates/sales/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row justify-content-between my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>
                    최신순
                </option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>
                    추천순
                </option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>
                    인기순
                </option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw"
                   value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary"
                        type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center" style="background-color:#02075D; color:#ffffff">
            <th>ID</th>
            <th>이용자</th>
{#            <th style="width:50%">제목</th>#}
            <th>지역</th>
            <th>건물명</th>
            <th>작성일자</th>
            <th>사용자 ID</th>
            <th>이미지</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <a href="{% url 'sales:detail' question.id %}">
                    {{ question.hcode}}
                </a>
            <td id="text1">{{ question.wname}}</td>

            <td id="text2">{{ question.wplace}}</td>

            <td id="text3">{{ question.port}}</td>

            <td id="text4">{{ question.create_date|date}}</td>

            <td id="text5">{{ question.author}}</td>

            <td class="text-truncate" style="max-width: 100px;">
                {% if question.upload_imgfile != '' and question.upload_imgfile != null %}
                <span class="badge badge-secondary py-1">
                    {{ question.upload_imgfile }}
                </span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">등록된 정보가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link"
               href="?page={{question_list.previous_page_number}}">
                이전
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{page_number}}">
                    {{page_number}}
                </a>
            </li>
            {% else %}
            <li class="page_item">
                <a class="page-link" href="?page={{page_number}}">
                    {{page_number}}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link"
               href="?page={{question_list.next_page_number}}">
                다음
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝 -->
    <a href="{% url 'sales:question_create' %}" class="btn btn-primary"
       style="background-color:#02075D; color:#ffffff">
        정보 등록
    </a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click',function(){
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click',function(){
        $("#kw").val($(".kw").val());
        $("#page").val(1); // 검색 버튼을 클릭할 경우 1페이부터 조회한다.
        $("#searchForm").submit();
    });
    $(".so").on('change',function(){
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}